version: '3.8'

services:
  springboot:
    image: onggiyonggi-registry.kr.ncr.ntruss.com/onggiyonggi:latest
    container_name: onggiyonggi-springboot
    ports:
      - "9000:9000"
    env_file:
      - .env.prod
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - backend
    restart: always

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - springboot
    networks:
      - backend
    restart: always

networks:
  backend:
    driver: bridge
